/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exceltools;

import java.io.File;
import java.io.IOException;

import org.apache.poi.EncryptedDocumentException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

public class App {
    public String getGreeting() {

        // エクセルファイルへアクセスするためのオブジェクト
        Workbook excel;
        try {
            excel = WorkbookFactory.create(new File("Sample.xlsx"));
        } catch (EncryptedDocumentException | IOException e) {
            e.printStackTrace();
        }

        // シート名がわかっている場合
        final Sheet sheet = excel.getSheet("Sheet1");

        // 0行目
        final Row row = sheet.getRow(0);

        // 0番目のセル
        final Cell cell = row.getCell(0);

        // 文字列の取得
        final String value = cell.getStringCellValue();

        //取得した文字列の表示
        System.out.println(value);

        return "Hello world.";
    }

    public static void main(final String[] args) {
        System.out.println(new App().getGreeting());
    }
}
